name: CI Test Step 1

on:
  push:
    branches:
      - ci-my-first-branch

permissions:
  contents: read
  issues: write

env:
  STEP_2_FILE: ".github/steps/2-step.md"

jobs:
  find_exercise:
    name: Retrouver l'Issue CI
    uses: ENSTASIMOV/exercise-toolkit-fr/.github/workflows/find-exercise-issue.yml@main
    with:
      issue-title-text: "Exercice : GitHub Basics CI"

  post_next_step_content:
    name: Afficher l'étape 2
    needs: [find_exercise]
    runs-on: ubuntu-latest
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ENSTASIMOV/exercise-toolkit-fr
          path: exercise-toolkit-fr
          ref: main

      - name: Confirmer l'étape
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit-fr/markdown-templates/step-feedback/step-finished-prepare-next-step.md
          vars: |
            next_step_number: 2

      - name: Publier l'étape 2
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_2_FILE }}

      - name: Publier le suivi
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit-fr/markdown-templates/step-feedback/watching-for-progress.md
